spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/socialapp
    username: postgres
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8081

elasticsearch:
  port: 9200
  clustername: socialapp-cluster
  host: localhost
  server: http://localhost:9200
